channels:
     - conda-forge
 dependencies:
     - dlib
     - numpy
     - scipy
     - opencv
     - face_recognition
     - streamlit==1.17
     - streamlit_webrtc
     - av
     - pandas
    





