channels:
     - conda-forge
 dependencies:
     - dlib
     - numpy
     - scipy
     - opencv
     - face_recognition
     
     - opencv-contrib-python==4.6.0.66
     - opencv-python==4.6.0.66
     - opencv-python-headless==4.5.4.60
    
     - pandas==1.3.5
     - pandas-datareader==0.9.0
     - pandas-gbq==0.17.9
     - pandas-profiling==1.4.1
     - streamlit==1.17
     - streamlit_webrtc
     - av
    





